from pathlib import Path
import asyncio
import sys
PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))
from search.provider.travily import travily_search
from search.provider.you import you_search
from search.provider.exa import exa_client
from retrieval.retrieval_decision_maker import plan_retrieval, plan_retrieval_async
from pprint import pprint
from API.travily_client import tavily_client
from API.you_client import you_client
from API.exa_client import exa_client
from retrieval.Unified_retrieval_manager import UnifiedRetrievalResult, normalize_provider_bundle

def _get_max_results(priority: str) -> int:
    """
    Determine retrieval breadth based on planner priority.
    """
    priority = priority.lower()

    if priority == "high":
        return 8

    if priority == "medium":
        return 5

    return 3


async def _call_tavily(
    query: str,
    intent: str,
    priority: str,
):
    """
    Execute a Tavily search based on RetrievalPlan metadata.

    Args:
        query: Expanded query generated by planner.
        intent: Planner classified intent.
        priority: high | medium | low

    Returns:
        Provider response bundle.
    """

    if not query:
        raise ValueError("query must not be empty")

    intent = (intent or "factoid").lower()

    # -----------------------------
    # Retrieval Strategy
    # -----------------------------

    topic = "general"
    search_depth = "advanced"
    include_raw_content = False

    if intent == "freshness":
        topic = "news"
        search_depth = "advanced"

    elif intent == "factoid":
        topic = "general"
        search_depth = "basic"

    elif intent == "research":
        topic = "general"
        search_depth = "advanced"
        include_raw_content = True

    elif intent == "technical_comparison":
        topic = "general"
        search_depth = "advanced"
        include_raw_content = True

    max_results = _get_max_results(priority)

    # -----------------------------
    # Execute Search
    # -----------------------------

    search_call = tavily_client.search

    kwargs = {
        "query": query,
        "topic": topic,
        "search_depth": search_depth,
        "max_results": max_results,
        "include_favicon": True,
        "include_raw_content": include_raw_content,
    }

    try:

        if asyncio.iscoroutinefunction(search_call):

            response = await search_call(**kwargs)

        else:

            response = await asyncio.to_thread(
                search_call,
                **kwargs,
            )

    except Exception as e:

        return {
            "provider": "tavily",
            "query": query,
            "intent": intent,
            "priority": priority,
            "status": "failed",
            "error": str(e),
            "response": None,
        }

    # -----------------------------
    # Return Provider Bundle
    # -----------------------------

    return {
        "provider": "tavily",
        "query": query,
        "intent": intent,
        "priority": priority,
        "status": "success",
        "response": response,
    }
# ===========+===========================+===========================+================
async def _call_you(
    query: str,
    intent: str,
    priority: str,
):
    """
    Execute a You.com search based on RetrievalPlan metadata.

    Args:
        query: Expanded query generated by planner.
        intent: Planner classified intent.
        priority: high | medium | low

    Returns:
        Provider response bundle.
    """

    if not query:
        raise ValueError("query must not be empty")

    max_results = _get_max_results(priority)

    kwargs = {
        "query": query,
        "count": max_results,
    }

    try:

        search_call = you_client.search.unified

        if asyncio.iscoroutinefunction(search_call):

            response = await search_call(**kwargs)

        else:

            response = await asyncio.to_thread(
                search_call,
                **kwargs,
            )

    except Exception as e:

        return {
            "provider": "you",
            "query": query,
            "intent": intent,
            "priority": priority,
            "status": "failed",
            "error": str(e),
            "response": None,
        }

    return {
        "provider": "you",
        "query": query,
        "intent": intent,
        "priority": priority,
        "status": "success",
        "response": response,
    }
# ===========+===========================+===========================+================
async def _call_exa(
    query: str,
    intent: str,
    priority: str,
):
    """
    Execute an Exa search based on RetrievalPlan metadata.

    Args:
        query: Expanded query generated by planner.
        intent: Planner classified intent.
        priority: high | medium | low

    Returns:
        Provider response bundle.
    """

    if not query:
        raise ValueError("query must not be empty")

    intent = (intent or "research").lower()
    max_results = _get_max_results(priority)

    contents = {"highlights": True}
    if intent in {"research", "technical_comparison", "coding"}:
        contents["text"] = True
    if intent in {"research", "technical_comparison"}:
        contents["summary"] = True

    kwargs = {
        "type": "auto",
        "num_results": max_results,
        "contents": contents,
    }

    search_call = exa_client.search

    try:
        if asyncio.iscoroutinefunction(search_call):
            response = await search_call(query, **kwargs)
        else:
            response = await asyncio.to_thread(
                search_call,
                query,
                **kwargs,
            )
    except Exception as e:
        return {
            "provider": "exa",
            "query": query,
            "intent": intent,
            "priority": priority,
            "status": "failed",
            "error": str(e),
            "response": None,
        }

    return {
        "provider": "exa",
        "query": query,
        "intent": intent,
        "priority": priority,
        "status": "success",
        "response": response,
    }
# ===========+===========================+===========================+================



async def retrivel_search(user_query: str) -> dict:
    """
    Plan retrieval, execute provider calls in parallel, and normalize results.
    """
    if not user_query or not user_query.strip():
        raise ValueError("user_query must not be empty")

    planned_retrieval = await plan_retrieval_async(user_query)

    tasks: list = []
    for plan in planned_retrieval:
        for tool in plan.tools:
            if tool == "exa":
                tasks.append(_call_exa(plan.query, plan.intent, plan.priority))
            elif tool == "tavily":
                tasks.append(_call_tavily(plan.query, plan.intent, plan.priority))
            elif tool == "you":
                tasks.append(_call_you(plan.query, plan.intent, plan.priority))
            else:
                raise ValueError(f"Unsupported tool: {tool}")

    if not tasks:
        return {"plans": planned_retrieval, "results": [], "failures": []}

    bundles = await asyncio.gather(*tasks)

    results: list[UnifiedRetrievalResult] = []
    failures: list[dict] = []
    for bundle in bundles:
        if bundle.get("status") != "success":
            failures.append(bundle)
            continue
        results.extend(normalize_provider_bundle(bundle))

    return {"plans": planned_retrieval, "results": results, "failures": failures}




# response = asyncio.run(retrivel_search("what happen is 1991 Ayodhya riots"))

# pprint(response)